### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by Memenymous**

### CODE REVIEW

**Comment by Owyn** [comment]
didn't your readme say it was incompatible with Pinky's proxy?

I thought mine still worked there... (can't test)

**Comment by Memenymous** [comment]
It is your readme :D

**Comment by Owyn** [comment]
> Works only on Pinky Proxy currently, broken on ToolBox

oh wait 🤔

**Comment by Owyn** [comment]
would be great if it could also be fixed for the ToolBox

**Comment by Memenymous** [comment]
Must work in both proxies

**Pull request merged**
